unsafe = ['EXPOSED_ANUS','EXPOSED_ARMPITS','COVERED_BELLY','EXPOSED_BELLY','COVERED_BUTTOCKS','EXPOSED_GENITALIA_M',
		'EXPOSED_BUTTOCKS','EXPOSED_FEET','COVERED_BREAST_F','EXPOSED_BREAST_F','COVERED_GENITALIA_F','EXPOSED_GENITALIA_F','EXPOSED_BREAST_M']
